// Mikisoq house data. Original rooms, not Microsoft Bob art.
// Door percentages are the painted door on stoop.png (320x180), not the window above it.

export const ROOMS = [
  { id: "family", src: "house/family.png?v=1" },
  { id: "study", src: "house/study.png?v=1" },
  { id: "kitchen", src: "house/kitchen.png?v=1" },
  { id: "den", src: "house/den.png?v=1" },
];

/** Painted front door on the red house, percent of stoop.png (320×180).
 *  Measured on the door leaf: x 75, y 73, 22×32 px. Not the fish racks. */
export const STOOP_DOOR = { x: 23.5, y: 40.5, w: 7, h: 18 };

/** Knock target. Kept equal to the painted door. */
export const KNOCK_SPOT = { x: 23.5, y: 40.5, w: 7, h: 18 };

export function overlapRatio(hit, target) {
  const width = Math.max(0, Math.min(hit.x + hit.w, target.x + target.w) - Math.max(hit.x, target.x));
  const height = Math.max(0, Math.min(hit.y + hit.h, target.y + target.h) - Math.max(hit.y, target.y));
  const area = hit.w * hit.h;
  if (area <= 0) return 0;
  return (width * height) / area;
}

export const THINGS = [
  { id: "fam-dict", room: "family", program: "dict", kind: "sprite", sprite: "obj-book", x: 40, y: 80, w: 10 },
  { id: "fam-cal", room: "family", program: "calendar", kind: "sprite", sprite: "obj-calendar", x: 86, y: 32, w: 8 },
  { id: "fam-clock", room: "family", program: "clock", kind: "sprite", sprite: "obj-clock", x: 57, y: 58, w: 7 },
  { id: "fam-door", room: "family", program: "door", kind: "sprite", sprite: "obj-door", x: 14, y: 82, w: 7 },
  { id: "stu-letter", room: "study", program: "letter", kind: "sprite", sprite: "obj-letter", x: 44, y: 70, w: 10 },
  { id: "stu-find", room: "study", program: "finder", kind: "sprite", sprite: "obj-glass", x: 62, y: 62, w: 7 },
  { id: "stu-door", room: "study", program: "door", kind: "sprite", sprite: "obj-door", x: 76, y: 60, w: 7 },
  { id: "kit-list", room: "kitchen", program: "lists", kind: "sprite", sprite: "obj-clip", x: 72, y: 52, w: 9 },
  { id: "kit-quiz", room: "kitchen", program: "quiz", kind: "sprite", sprite: "obj-book", x: 34, y: 74, w: 10 },
  { id: "kit-door", room: "kitchen", program: "door", kind: "sprite", sprite: "obj-door", x: 78, y: 62, w: 7 },
  { id: "den-addr", room: "den", program: "address", kind: "sprite", sprite: "obj-book", x: 30, y: 78, w: 10 },
  { id: "den-about", room: "den", program: "about", kind: "baked", x: 27, y: 16, w: 20, h: 28 },
  { id: "den-door", room: "den", program: "door", kind: "sprite", sprite: "obj-door", x: 70, y: 66, w: 7 },
];

export const en = {
  "greet.empty": "Knock. I'll get the door. I'm Mikisoq.",
  "greet.named": "Knock, or pick your name. I'm Mikisoq.",
  askName: "What should I call you?",
  askNameNew: "A new name on the door. What should I call you?",
  who: "Who's there? Pick your name, or tell me you're new.",
  whichRoom: "Which room is just yours? The others are the rest of the house.",
  welcomeBack: "Welcome back, {name}. The family room kept your place.",
  knock: "Knock",
  someoneNew: "Someone new",
  yourName: "Your name",
  thatsMe: "That's me",
  thisRoomMine: "This room is mine",
  ok: "OK",
  goOn: "Go on",
  yours: "yours",
  "lang.en": "English",
  "lang.da": "Dansk",
  "room.family": "Family room",
  "room.study": "Study",
  "room.kitchen": "Kitchen",
  "room.den": "Den",
  "blurb.family": "The book, the clock, the calendar.",
  "blurb.study": "Letters and word stems.",
  "blurb.kitchen": "Lists and a quiz over the counter.",
  "blurb.den": "The room that is just yours.",
  "thing.dict": "Dictionary",
  "hint.dict": "Look up a word",
  "thing.calendar": "Calendar",
  "hint.calendar": "A note on a day",
  "thing.clock": "Clock",
  "hint.clock": "What time it is",
  "thing.letter": "Letter writer",
  "hint.letter": "Notes kept in the desk",
  "thing.finder": "Word finder",
  "hint.finder": "Line up a stem",
  "thing.lists": "Household lists",
  "hint.lists": "Check things off",
  "thing.quiz": "Word quiz",
  "hint.quiz": "Four choices",
  "thing.address": "Address book",
  "hint.address": "People to remember",
  "thing.about": "About this house",
  "hint.about": "The round window",
  "thing.door": "Door",
  "hint.door": "Other rooms",
  otherRooms: "Other rooms",
  findProgram: "Find a program",
  moveThings: "Move things",
  doneMoving: "Done moving",
  showClicks: "Show what I can click",
  hideMarks: "Hide the marks",
  changeLight: "Change the light",
  howMuchTalk: "How much I talk",
  showAround: "Show me around",
  soundOn: "Sound on",
  soundOff: "Sound off",
  stepOutside: "Step outside",
  whereTo: "Where to?",
  stayHere: "Stay here",
  neverMind: "Never mind",
  dragBanner: "Drag what I brought in. The painting stays.",
  moveSay: "Drag the loose things. Click me again when the room feels right.",
  lightSay: "{light} light.",
  "light.day": "Day",
  "light.lamp": "Lamp",
  "light.evening": "Evening",
  "talk.title": "How much should I talk?",
  "talk.chatty": "Talk a lot",
  "talk.helpful": "When it's new",
  "talk.quiet": "Only if I ask",
  "talk.leave": "Leave it",
  "talk.say.quiet": "I'll keep quiet unless you click me.",
  "talk.say.chatty": "I'll chime in. You can tell me to stop.",
  "talk.say.helpful": "I'll explain a thing the first time you open it.",
  "tour.0": "Welcome in. This is not a desktop. It's a house. I'm Mikisoq.",
  "tour.1": "The things in the room are the programs. The book is the dictionary. Click a thing to open it.",
  "tour.2": "A door goes to another room. Every room is another place to keep things. There is no start menu.",
  "tour.3": "Click me when you want a hand. Press F1 if you can't tell what is alive. I'll stay in the corner.",
  "tip.dict": "Type a word in Kalaallisut or English. I'll look through the Chicago dictionary. The glosses are in English.",
  "tip.calendar": "Click a day and leave yourself a note. I don't do reminders. I'm a dog, not a bell.",
  "tip.clock": "It tells the time. The mantel already had one. This one you can actually ask.",
  "tip.letter": "Write it here. When you leave the desk, I keep it.",
  "tip.finder": "Give me the start of a word and I'll line up matching stems. This is the shelf, not the full deconstructor.",
  "tip.lists": "Lists live in the kitchen. Check them off. Add your own.",
  "tip.quiz": "I'll borrow four words. You pick the one that means what I say. The meaning is in English.",
  "tip.address": "Names you want to remember. This room is yours, so they stay with you.",
  "tip.about": "A house instead of a row of icons. I'm Mikisoq. The words belong to Oqaasileriffik.",
  "list.lookup": "Words to look up",
  "list.house": "House",
  "list.knock": "Knock before you come in",
  back: "Back to the room",
  "dict.prompt": "Kalaallisut or English",
  "dict.placeholder": "Type to search",
  "stem.prompt": "Start of a word",
  "stem.placeholder": "qimme…",
  "dict.error": "The words didn't arrive. The shelf is still here.",
  "dict.loading": "Opening the dictionary…",
  "stem.empty": "I'll line up lexemes and stems that start like that. Not a full morphological parse.",
  "dict.empty": "{count} entries. Nothing is listed until you type.",
  nothing: "Nothing matched.",
  stemLabel: "stem {stem}",
  prev: "Prev",
  next: "Next",
  prevMonth: "Previous month",
  nextMonth: "Next month",
  notePh: "A note for this day",
  add: "Add",
  remove: "Remove",
  nothingWritten: "Nothing written.",
  untitled: "Untitled",
  newLetter: "New letter",
  deskEmpty: "The desk is empty.",
  title: "Title",
  letter: "Letter",
  throwOut: "Throw this one out",
  pickLetter: "Pick a letter, or start one.",
  newList: "New list",
  addLine: "Add a line",
  nothingOnList: "Nothing on this list.",
  makeList: "Make a list.",
  name: "Name",
  note: "Note",
  noteAny: "A word, a place, anything",
  keep: "Keep this one",
  nobody: "Nobody written down yet.",
  "quiz.error": "I need the dictionary for this, and it didn't arrive.",
  "quiz.loading": "Shuffling the words…",
  "quiz.prompt": "Which word means “{gloss}”?",
  "quiz.yes": "That's the one.",
  "quiz.no": "It was {answer}.",
  "quiz.another": "Another word",
  "quiz.score": "This sitting: {ok} / {n}",
  "quiz.empty": "I couldn't deal a fair question from these words.",
  "about.1": "Mikisoq is the sled dog at the door. The house is the computer: rooms instead of a desktop, things instead of icons, and a guide in the corner instead of a start menu.",
  "about.2": "Click a thing to open it. Click Mikisoq for the menu. Doors go to other rooms. F1 marks what you can touch. Loose things can be dragged; the painted room stays where it was built.",
  "about.3": "Your private room is the {room}. Letters, lists, and the address book stay in this browser, on this computer.",
  "week.0": "Mon",
  "week.1": "Tue",
  "week.2": "Wed",
  "week.3": "Thu",
  "week.4": "Fri",
  "week.5": "Sat",
  "week.6": "Sun",
  toWindows: "Back to Windows",
};

export const da = {
  "greet.empty": "Bank på. Jeg lukker op. Jeg er Mikisoq.",
  "greet.named": "Bank på, eller vælg dit navn. Jeg er Mikisoq.",
  askName: "Hvad skal jeg kalde dig?",
  askNameNew: "Et nyt navn på døren. Hvad skal jeg kalde dig?",
  who: "Hvem er det? Vælg dit navn, eller sig at du er ny.",
  whichRoom: "Hvilket rum er kun dit? De andre er resten af huset.",
  welcomeBack: "Velkommen tilbage, {name}. Stuen har holdt din plads.",
  knock: "Bank på",
  someoneNew: "En ny",
  yourName: "Dit navn",
  thatsMe: "Det er mig",
  thisRoomMine: "Det her rum er mit",
  ok: "OK",
  goOn: "Videre",
  yours: "dit",
  "lang.en": "English",
  "lang.da": "Dansk",
  "room.family": "Stue",
  "room.study": "Arbejdsværelse",
  "room.kitchen": "Køkken",
  "room.den": "Kammer",
  "blurb.family": "Bogen, uret og kalenderen.",
  "blurb.study": "Breve og ordstammer.",
  "blurb.kitchen": "Lister og en quiz ved bordet.",
  "blurb.den": "Rummet der kun er dit.",
  "thing.dict": "Ordbog",
  "hint.dict": "Slå et ord op",
  "thing.calendar": "Kalender",
  "hint.calendar": "En note på en dag",
  "thing.clock": "Ur",
  "hint.clock": "Hvad klokken er",
  "thing.letter": "Brev",
  "hint.letter": "Noter i skrivebordet",
  "thing.finder": "Ordfinder",
  "hint.finder": "Stil en stamme op",
  "thing.lists": "Husholdningslister",
  "hint.lists": "Sæt flueben",
  "thing.quiz": "Ordquiz",
  "hint.quiz": "Fire muligheder",
  "thing.address": "Adressebog",
  "hint.address": "Folk du vil huske",
  "thing.about": "Om huset",
  "hint.about": "Det runde vindue",
  "thing.door": "Dør",
  "hint.door": "Andre rum",
  otherRooms: "Andre rum",
  findProgram: "Find et program",
  moveThings: "Flyt ting",
  doneMoving: "Færdig med at flytte",
  showClicks: "Vis hvad jeg kan trykke på",
  hideMarks: "Skjul mærkerne",
  changeLight: "Skift lyset",
  howMuchTalk: "Hvor meget jeg snakker",
  showAround: "Vis mig rundt",
  soundOn: "Lyd til",
  soundOff: "Lyd fra",
  stepOutside: "Gå udenfor",
  whereTo: "Hvorhen?",
  stayHere: "Bliv her",
  neverMind: "Lad være",
  dragBanner: "Træk i det jeg har sat ind. Maleriet bliver.",
  moveSay: "Træk i de løse ting. Klik på mig igen, når rummet sidder rigtigt.",
  lightSay: "Lyset er sat til {light}.",
  "light.day": "dag",
  "light.lamp": "lampe",
  "light.evening": "aften",
  "talk.title": "Hvor meget skal jeg snakke?",
  "talk.chatty": "Snak meget",
  "talk.helpful": "Når det er nyt",
  "talk.quiet": "Kun hvis jeg spørger",
  "talk.leave": "Lad det være",
  "talk.say.quiet": "Jeg tier, medmindre du klikker på mig.",
  "talk.say.chatty": "Jeg blander mig. Du kan sige til, når jeg skal stoppe.",
  "talk.say.helpful": "Jeg forklarer en ting, første gang du åbner den.",
  "tour.0": "Velkommen ind. Det her er ikke et skrivebord. Det er et hus. Jeg er Mikisoq.",
  "tour.1": "Tingene i rummet er programmerne. Bogen er ordbogen. Klik på en ting for at åbne den.",
  "tour.2": "En dør går til et andet rum. Hvert rum er et sted at have ting. Der er ingen startmenu.",
  "tour.3": "Klik på mig, når du vil have hjælp. Tryk på F1, hvis du ikke kan se, hvad der er levende. Jeg bliver i hjørnet.",
  "tip.dict": "Skriv et ord på kalaallisut eller engelsk. Jeg leder i Chicago-ordbogen. Forklaringerne er på engelsk.",
  "tip.calendar": "Klik på en dag og læg en note. Jeg minder dig ikke om noget. Jeg er en hund, ikke en klokke.",
  "tip.clock": "Den siger, hvad klokken er. Kaminen havde allerede et ur. Det her kan du faktisk spørge.",
  "tip.letter": "Skriv det her. Når du går fra skrivebordet, gemmer jeg det.",
  "tip.finder": "Giv mig starten af et ord, så stiller jeg stammer op, der passer. Det her er hylden, ikke den fulde deling.",
  "tip.lists": "Listerne bor i køkkenet. Sæt flueben. Lav dine egne.",
  "tip.quiz": "Jeg låner fire ord. Du vælger det, der betyder det, jeg siger. Betydningen står på engelsk.",
  "tip.address": "Navne du vil huske. Rummet er dit, så de bliver hos dig.",
  "tip.about": "Et hus i stedet for en række ikoner. Jeg er Mikisoq. Ordene tilhører Oqaasileriffik.",
  "list.lookup": "Ord jeg vil slå op",
  "list.house": "Huset",
  "list.knock": "Bank på, før du kommer ind",
  back: "Tilbage til rummet",
  "dict.prompt": "Kalaallisut eller engelsk",
  "dict.placeholder": "Skriv for at søge",
  "stem.prompt": "Starten af et ord",
  "stem.placeholder": "qimme…",
  "dict.error": "Ordene kom ikke frem. Hylden er her stadig.",
  "dict.loading": "Åbner ordbogen…",
  "stem.empty": "Jeg stiller ord og stammer op, der starter sådan. Det er ikke en fuld orddeling.",
  "dict.empty": "{count} opslag. Der vises ikke noget, før du skriver.",
  nothing: "Ingen træffere.",
  stemLabel: "stamme {stem}",
  prev: "Forrige",
  next: "Næste",
  prevMonth: "Forrige måned",
  nextMonth: "Næste måned",
  notePh: "En note til den dag",
  add: "Tilføj",
  remove: "Fjern",
  nothingWritten: "Ikke skrevet noget.",
  untitled: "Uden titel",
  newLetter: "Nyt brev",
  deskEmpty: "Skrivebordet er tomt.",
  title: "Titel",
  letter: "Brev",
  throwOut: "Smid det her ud",
  pickLetter: "Vælg et brev, eller begynd på et.",
  newList: "Ny liste",
  addLine: "Tilføj en linje",
  nothingOnList: "Ikke noget på listen.",
  makeList: "Lav en liste.",
  name: "Navn",
  note: "Note",
  noteAny: "Et ord, et sted, hvad som helst",
  keep: "Gem den her",
  nobody: "Ingen skrevet ned endnu.",
  "quiz.error": "Jeg skal bruge ordbogen til det her, og den kom ikke frem.",
  "quiz.loading": "Blander ordene…",
  "quiz.prompt": "Hvilket ord har den engelske betydning „{gloss}“?",
  "quiz.yes": "Det er den.",
  "quiz.no": "Det var {answer}.",
  "quiz.another": "Et ord til",
  "quiz.score": "Denne omgang: {ok} / {n}",
  "quiz.empty": "Jeg kunne ikke stille et rimeligt spørgsmål ud fra de her ord.",
  "about.1": "Mikisoq er slædehunden ved døren. Huset er computeren: rum i stedet for et skrivebord, ting i stedet for ikoner, og en hjælper i hjørnet i stedet for en startmenu.",
  "about.2": "Klik på en ting for at åbne den. Klik på Mikisoq for menuen. Døre går til andre rum. F1 viser, hvad du kan røre ved. Løse ting kan trækkes; det malede rum bliver, hvor det blev bygget.",
  "about.3": "Dit eget rum er {room}. Breve, lister og adressebogen bliver i den her browser, på den her computer.",
  "week.0": "Man",
  "week.1": "Tir",
  "week.2": "Ons",
  "week.3": "Tor",
  "week.4": "Fre",
  "week.5": "Lør",
  "week.6": "Søn",
  toWindows: "Tilbage til Windows",
};

export const catalogs = { en, da };

export function t(locale, key, vars) {
  let raw = catalogs[locale][key];
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (match, name) => (vars[name] != null ? String(vars[name]) : match));
}

const TOUR = ["tour.0", "tour.1", "tour.2", "tour.3"];

export function tourLines(locale) {
  return TOUR.map((key) => t(locale, key));
}

/** Four choices when the pool allows it. `random` is injectable for tests. */
export function pickQuestion(entries, random = Math.random) {
  const pool = [];
  const seenGloss = new Set();
  for (const entry of entries) {
    const lexeme = String(entry.lexeme || "").trim();
    const gloss = String(entry.gloss_en || "").trim();
    if (lexeme.length < 2 || gloss.length <= 3) continue;
    const key = gloss.toLowerCase();
    if (seenGloss.has(key)) continue;
    seenGloss.add(key);
    pool.push({ lexeme, gloss });
  }
  if (pool.length < 4) return null;
  const bag = pool.slice();
  for (let i = bag.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    const swap = bag[i];
    bag[i] = bag[j];
    bag[j] = swap;
  }
  const answer = bag[0];
  const choices = bag.slice(0, 4);
  for (let i = choices.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    const swap = choices[i];
    choices[i] = choices[j];
    choices[j] = swap;
  }
  return { gloss: answer.gloss, answer: answer.lexeme, choices: choices.map((c) => c.lexeme) };
}
