// retr-oq games/programs catalogue -- not wired into any theme, this is a
// reference data structure only (source of truth for the README matrix).
// Update both when a theme gains or loses a game/easter egg.
//
// kind: "core" (OQ!/DECON, present everywhere), "game" (a real minigame),
// "demo" (visual/audio toggle, not interactive play), "egg" (undocumented
// or joke easter egg).
window.OqGames = {
  games: [
    { id: "oq", name: "OQ! dictionary", kind: "core" },
    { id: "decon", name: "Word Deconstructor", kind: "core" },
    { id: "morph", name: "MORPH!", kind: "game" },
    { id: "kal-q", name: "Super KAL-Q! (Klax)", kind: "game" },
    { id: "konami", name: "Konami Code", kind: "egg" },
    { id: "doom", name: "DOOM", kind: "egg" },
    { id: "boing", name: "Boing Ball", kind: "demo" },
    { id: "copper", name: "Copper bars", kind: "demo" },
    { id: "panic", name: "Kernel panic", kind: "egg" },
    { id: "kde-rain", name: "Compiz rain", kind: "demo" },
    { id: "kde-cube", name: "Desktop cube", kind: "demo" },
    { id: "solitaire", name: "Solitaire (joke)", kind: "egg" },
    { id: "hotdog", name: "Hot Dog Stand scheme", kind: "egg" },
    { id: "credits", name: "Hidden credits", kind: "egg" },
    { id: "ss-flying", name: "Flying Windows", kind: "demo" },
    { id: "ss-maze", name: "3D Maze", kind: "demo" },
    { id: "ss-pipes", name: "3D Pipes", kind: "demo" },
    { id: "ss-backrooms", name: "Backrooms", kind: "demo" },
    { id: "ss-backrooms-ii", name: "Backrooms II", kind: "demo" },
    { id: "ss-cga", name: "CGA starfield", kind: "demo" },
    { id: "ss-raster", name: "Raster stars", kind: "demo" },
    { id: "ss-mac-stars", name: "1-bit stars", kind: "demo" },
    { id: "ss-afterdark", name: "Starry night", kind: "demo" },
    { id: "ss-boing-idle", name: "Boing (idle)", kind: "demo" },
    { id: "ss-backspace", name: "BackSpace", kind: "demo" },
    { id: "ss-attract", name: "Attract mode", kind: "demo" },
    { id: "ss-kde-gl", name: "KDE GL savers", kind: "demo" },
  ],
  matrix: {
    dos: ["doom", "ss-cga"],
    c64: ["morph", "ss-raster"],
    mac1984: ["ss-mac-stars"],
    nes: ["konami", "ss-attract"],
    amiga: ["boing", "copper", "ss-boing-idle"],
    gb: ["morph", "konami", "ss-attract"],
    gg: ["konami", "ss-attract"],
    compy: ["konami", "ss-attract"],
    snes: ["kal-q", "konami", "ss-attract"],
    win31: ["solitaire", "credits", "ss-flying"],
    next: ["panic", "ss-backspace"],
    mac8: ["ss-afterdark"],
    win98: ["hotdog", "ss-maze", "ss-pipes", "ss-backrooms"],
    beos: ["panic"],
    xp: ["ss-pipes", "ss-backrooms-ii"],
    kde: ["kde-rain", "kde-cube", "ss-kde-gl"],
    win7: ["ss-pipes"],
  },
};
